### ISSUE TITLE
InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.

### ISSUE THREAD

**Issue by duancaohui** [tmquan/RefineGAN#11]
I specially setup the configurations for the RefineGAN:
```
python 2.7
tensorflow==1.5.1 
tensorpack==0.8.2
......
```
All seems to be going well, I successfully trained the model several days ago.
However, When I test or retrain it, a mistake appeared as follows, When I change NCHW to 'NHWC', more mistakes appeared, can you help me, thanks!

```
`0%|          |0/100[00:00<?,?it/s]2019-06-25 10:26:43.160707: E tensorflow/core
/common_runtime/executor.cc:651] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gen/recon/recon/recon/d3/deconv_i/stack, gen/recon/d3/deconv_i/W/read, gen/recon/recon/recon/e3/conv_o/LeakyRelu/Maximum)]]

2019-06-25 10:26:43.225819: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/duan/tensorflow/RefineGAN/exp_dset_RefineGAN_mask_strategy_rate.py", line 4, in <module>
    main()
[0625 10:26:43 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
  File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 414, in main
    max_epoch=500
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 318, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 296, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 182, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 261, in main_loop
    self.run_step()  # implemented by subclass
  File "/home/duan/tensorflow/RefineGAN/GAN.py", line 119, in run_step
    self.hooked_sess.run(self.d_min)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 539, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1013, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 941, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gen/recon/recon/recon/d3/deconv_i/stack, gen/recon/d3/deconv_i/W/read, gen/recon/recon/recon/e3/conv_o/LeakyRelu/Maximum)]]

Caused by op u'gen/recon/recon/recon/d3/deconv_i/conv2d_transpose', defined at:
  File "/home/duan/tensorflow/RefineGAN/exp_dset_RefineGAN_mask_strategy_rate.py", line 4, in <module>
    main()
  File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 380, in main
    trainer = SeparateGANTrainer(ds_train, model, g_period=1, d_period=1)
  File "/home/duan/tensorflow/RefineGAN/GAN.py", line 104, in __init__
    tower_func(*input.get_input_tensors())
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/tower.py", line 207, in __call__
    output = self._tower_fn(*args)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/graph_builder/model_desc.py", line 116, in build_graph
    self._build_graph(inputs)
  File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 99, in _build_graph
    Sn2 = self.generator(M2)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/scope_utils.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 51, in generator
    return arch_generator(img)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/scope_utils.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/home/duan/tensorflow/RefineGAN/Utils.py", line 262, in arch_generator
    d3 = residual_dec('d3',    e3, NB_FILTERS*4)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/home/duan/tensorflow/RefineGAN/Utils.py", line 240, in residual_dec
    .Deconv2D('deconv_i', chan, stride=1)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/linearwrap.py", line 48, in layer_func
    ret = layer(name, self._t, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/tflayer.py", line 65, in decorated_func
    return func(inputs, **ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/conv2d.py", line 169, in Deconv2D
    ret = layer.apply(inputs, scope=tf.get_variable_scope())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 762, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 652, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/convolutional.py", line 1302, in call
    data_format=utils.convert_data_format(self.data_format, ndim=4))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1215, in conv2d_transpose
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 817, in conv2d_backprop_input
    dilations=dilations, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
	 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gp`
```

**Comment by HaiDafu** [comment]
It is recommended that you uninstall tensorflow-cpu and install tensorflow_gpu==1.4.0. If I remember correctly, tensorflow-cpu does not seem to support 'NHWC'.Please configure the running environment according to the libraries required by the original author.


------------------ 原始邮件 ------------------
发件人: "Caohui"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 上午10:41
收件人: "tmquan/RefineGAN"<RefineGAN@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [tmquan/RefineGAN] InvalidArgumentError (see above for traceback):Conv2DCustomBackpropInputOp only supports NHWC. (#11)




I specially setup the configurations for the RefineGAN:
 python 2.7
 tensorflow==1.5.1
 tensorpack==0.8.2
 ......
 All seems to be going well, I successfully trained the model several days ago.
 However, When I test or retrain it, a mistake appeared as follows, When I change NCHW to 'NHWC', more mistakes appeared, can you help me, thanks!
 
`0%|          |0/100[00:00<?,?it/s]2019-06-25 10:26:43.160707: E tensorflow/core
 /common_runtime/executor.cc:651] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gen/recon/recon/recon/d3/deconv_i/stack, gen/recon/d3/deconv_i/W/read, gen/recon/recon/recon/e3/conv_o/LeakyRelu/Maximum)]]
 
2019-06-25 10:26:43.225819: W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
 Traceback (most recent call last):
 File "/home/duan/tensorflow/RefineGAN/exp_dset_RefineGAN_mask_strategy_rate.py", line 4, in 
 main()
 [0625 10:26:43 @input_source.py:149] EnqueueThread QueueInput/input_queue Exited.
 File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 414, in main
 max_epoch=500
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 318, in train_with_defaults
 steps_per_epoch, starting_epoch, max_epoch)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 296, in train
 self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/utils/argtools.py", line 182, in wrapper
 return func(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/train/base.py", line 261, in main_loop
 self.run_step()  # implemented by subclass
 File "/home/duan/tensorflow/RefineGAN/GAN.py", line 119, in run_step
 self.hooked_sess.run(self.d_min)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 539, in run
 run_metadata=run_metadata)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1013, in run
 run_metadata=run_metadata)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1104, in run
 raise six.reraise(*original_exc_info)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1089, in run
 return self._sess.run(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1161, in run
 run_metadata=run_metadata)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 941, in run
 return self._sess.run(*args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
 run_metadata_ptr)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
 feed_dict_tensor, options, run_metadata)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
 options, run_metadata)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
 raise type(e)(node_def, op, message)
 tensorflow.python.framework.errors_impl.InvalidArgumentError: Conv2DCustomBackpropInputOp only supports NHWC.
 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](gen/recon/recon/recon/d3/deconv_i/stack, gen/recon/d3/deconv_i/W/read, gen/recon/recon/recon/e3/conv_o/LeakyRelu/Maximum)]]
 
Caused by op u'gen/recon/recon/recon/d3/deconv_i/conv2d_transpose', defined at:
 File "/home/duan/tensorflow/RefineGAN/exp_dset_RefineGAN_mask_strategy_rate.py", line 4, in 
 main()
 File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 380, in main
 trainer = SeparateGANTrainer(ds_train, model, g_period=1, d_period=1)
 File "/home/duan/tensorflow/RefineGAN/GAN.py", line 104, in init
 tower_func(*input.get_input_tensors())
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/tower.py", line 207, in call
 output = self._tower_fn(*args)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/graph_builder/model_desc.py", line 116, in build_graph
 self._build_graph(inputs)
 File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 99, in _build_graph
 Sn2 = self.generator(M2)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/scope_utils.py", line 43, in wrapper
 return func(*args, **kwargs)
 File "/home/duan/tensorflow/RefineGAN/RefineGAN.py", line 51, in generator
 return arch_generator(img)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/tfutils/scope_utils.py", line 43, in wrapper
 return func(args, **kwargs)
 File "/home/duan/tensorflow/RefineGAN/Utils.py", line 262, in arch_generator
 d3 = residual_dec('d3',    e3, NB_FILTERS4)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
 outputs = func(*args, **actual_args)
 File "/home/duan/tensorflow/RefineGAN/Utils.py", line 240, in residual_dec
 .Deconv2D('deconv_i', chan, stride=1)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/linearwrap.py", line 48, in layer_func
 ret = layer(name, self._t, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
 outputs = func(*args, **actual_args)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/tflayer.py", line 65, in decorated_func
 return func(inputs, **ret)
 File "/usr/local/lib/python2.7/dist-packages/tensorpack/models/conv2d.py", line 169, in Deconv2D
 ret = layer.apply(inputs, scope=tf.get_variable_scope())
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 762, in apply
 return self.call(inputs, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 652, in call
 outputs = self.call(inputs, *args, **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/convolutional.py", line 1302, in call
 data_format=utils.convert_data_format(self.data_format, ndim=4))
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1215, in conv2d_transpose
 name=name)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 817, in conv2d_backprop_input
 dilations=dilations, name=name)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
 op_def=op_def)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
 op_def=op_def)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in init
 self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access
 
InvalidArgumentError (see above for traceback): Conv2DCustomBackpropInputOp only supports NHWC.
 [[Node: gen/recon/recon/recon/d3/deconv_i/conv2d_transpose = Conv2DBackpropInput[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gp`
