### ISSUE TITLE
AssertionError: 1 != 3

### ISSUE THREAD

**Issue by duancaohui** [tmquan/RefineGAN#7]
When the fisrt epoch completed, a error occurred as follows:
`2019-01-08 19:50:59.606335: W tensorflow/core/kernels/queue_base.cc:295] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
  File "/home/duan/deeplearning/tensorflow/RefineGAN-master/RefineGAN.py", line 452, in <module>
    max_epoch=500
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 341, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 313, in train
    self.main_loop(steps_per_epoch, starting_epoch, max_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/train/base.py", line 285, in main_loop
    self._callbacks.trigger_epoch()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/group.py", line 97, in _trigger_epoch
    cb.trigger_epoch()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 149, in trigger_epoch
    self._trigger_epoch()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 155, in _trigger_epoch
    self.trigger()
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/callbacks/base.py", line 158, in trigger
    self._trigger()
  File "/home/duan/deeplearning/tensorflow/RefineGAN-master/RefineGAN.py", line 358, in _trigger
    vis_train =  np.array(self.pred(lst)[0])
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/predict/base.py", line 39, in __call__
    output = self._do_call(dp)
  File "/usr/local/lib/python3.5/dist-packages/tensorpack/predict/base.py", line 119, in _do_call
    "{} != {}".format(len(dp), len(self.input_tensors))
AssertionError: 1 != 3`

I carefully check this Error line by line, and find that the error  occurred when execute 
vis_train =  np.array(self.pred(lst)[0])
len(lst )=1!!!, in fact, len(lst)=3, I don,t know why

**Comment by tmquan** [comment]
Could you please try python 2.7?
This code was not with python 3.x
