### ISSUE TITLE
Problems when training

### ISSUE THREAD

**Issue by Jhhhha** [tmquan/RefineGAN#8]
I have tried training the model following your command, but something wrong occurs as below.
command:
```
python exp_knees_RefineGAN_mask_radial_1.py       --gpu='0'     --imageDir='data/knees/db_train/'        --labelDir='data/knees/db_train/'        --maskDir='data/mask/radial/mask_1/
```

Error raised:
```
Traceback (most recent call last):
  File "exp_knees_RefineGAN_mask_radial_1.py", line 4, in <module>
    main()
  File "/home/jhhhha/Documents/AI/RefineGAN/RefineGAN.py", line 411, in main
    trainer = SeparateGANTrainer(ds_train, model, g_period=1, d_period=1)
  File "/home/jhhhha/Documents/AI/RefineGAN/GAN.py", line 106, in __init__
    cbs = input.setup(model.get_inputs_desc())
  File "/home/jhhhha/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/home/jhhhha/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 76, in get_inputs_desc
    return self.get_input_signature()
  File "/home/jhhhha/anaconda3/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 200, in wrapper
    value = func(*args, **kwargs)
  File "/home/jhhhha/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 86, in get_input_signature
    inputs = self.inputs()
  File "/home/jhhhha/anaconda3/lib/python3.6/site-packages/tensorpack/graph_builder/model_desc.py", line 116, in inputs
    raise NotImplementedError()
NotImplementedError
```

**Comment by tmquan** [comment]
Please use python 2.7 instead, this was not tested with python 3

**Comment by HaiDafu** [comment]
I installed the corresponding version of the library as required, and then changed the common functions in the program, such as print, range and so on, into Python 3 grammar. After this change, the program can run under Python 3.
